name: ffmpeg_kit_flutter_platform_interface
description: A common platform interface for ffmpeg_kit_flutter plugin.
repository: https://github.com/rayonstudios/ffmpeg-kit
issue_tracker: https://github.com/rayonstudios/ffmpeg-kit/issues
homepage: https://github.com/rayonstudios/ffmpeg-kit

version: 0.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
